/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;

import java.net.MalformedURLException;
import java.net.SocketException;

public class App {
    public void getGreeting() throws InterruptedException, MalformedURLException, SocketException {

        // This is to remove unnecessary warnings from your console
        System.setProperty("java.util.logging.config.file", "logging.properties");
        // Initialize your test class
        GoogleForms forms = new GoogleForms();
        // Call the test case function
        forms.testCase01();
        //END Tests
        forms.endTest();
    }

    public static void main(String[] args) throws InterruptedException, MalformedURLException, SocketException {
        new App().getGreeting();
    }
}
